package watchvideo.dailytrend.Earnmoney_6.RealMoney_104;

import watchvideo.dailytrend.Earnmoney_6.EarnMoney_104.moneyapp_3;
import java.util.ArrayList;
import java.util.HashMap;

public class RealMoney_105 {
    public static final int ADS_INSTALL = 4;
    public static final String ALL_LANG_ID = "-10";
    public static final int BANNER_IMAGES = 2;
    public static final int BIG_BANNER_AD = 17;
    public static final String BRODCAST_REFRASH_SAVED_LIST = "brodcast_refrash_saved_list";
    public static final int CALL_DOWNLOAD_API = 0;
    public static final int CALL_LINE_API = 0;
    public static final int CALL_VIEW_API = 0;
    public static int CurrantPos = 0;
    public static final int DEFAULT_ITEM_TYPE = -11;
    public static final String EXTRA_IDENTIFYER = "extra_identifyer";
    public static final String EXTRA_IS_FROM_POPULAR = "extra_is_from_popular";
    public static final String EXTRA_PAGE = "EXTRA_PAGE";
    public static final String EXTRA_POS = "extra_pos";
    public static final String EXTRA_SEARCHED_IMAGE_TITLE = "extra_searched_image_title";
    public static final String EXTRA_SEARCH_VALUE = "extra_search_value";
    public static final String EXTRA_THRESHOL = "EXTRA_THRESHOL";
    public static final String EXTRA_VIDEO_ARRAY = "extra_vide_array";
    public static final String EXTRA_VIDEO_ID = "extra_video_id";
    public static final String EXTRA_VIDEO_INDENTIFYER = "extra_video_indentifyer";
    public static final String EXTRA_VIDEO_MODEL = "extra_video_model";
    public static final int FEATURE_VIDEO = 1;
    public static final int FEATURE_VIDEO_TITLE = 6;
    public static final int FRAGMENT_HOME_ID = 6;
    public static final int FRAGMENT_POPULAR_ID = 7;
    public static final int FRAGMENT_SAVED_ID = 9;
    public static final int FROM_CATEGORY_SEARCH = 12;
    public static final int FROM_FEATURE_VIDEO_LIST = 8;
    public static final int FROM_LANG_SEARCH = 13;
    public static final int FROM_SEARCH_VIDEO_LIST = 10;
    public static final int FROM_SINGLE_VIDEO_ID = 11;
    public static final int FROM_SUGG_SEARCH = 17;
    public static final int HOME_NEW_TO_OLD_API = 1;
    public static final int HOME_POPLULAR_API = 0;
    public static final int HOME_RANDOM_API = 2;
    public static final int IMG_BANNER_APP = 8;
    public static final int IMG_BANNER_CATEGORY = 3;
    public static final int IMG_BANNER_LANG = 5;
    public static final int IMG_BANNER_MAIL = 7;
    public static final int IMG_BANNER_TAG = 4;
    public static final int IMG_BANNER_URL = 6;
    public static final int IMG_BANNER_VIDEO = 2;
    public static final String INTERNET_CONNECTION_ISSUE = "No internet";
    public static int IS_FULLSCREEN_VIDEOS = 0;
    public static final int ITEM = 0;
    public static int LANDSCAPE_VIDEOS = 1;
    public static final int LIST_TITLE = 14;
    public static final int LOAD_MORE = 5;
    public static final int MOBILE_LIST_DATA_LIMIT = 24;
    public static final int NOTIFICATION_LIST_ITEM = 15;
    public static final String NO_DATA_FOUND = "No data found";
    public static final String OTHER_LAND_ID = "-11";
    public static final String PLZ_TRY_AGAIN = "Something want wrong please try again later";
    public static final int PROMO_BANER = 3;
    public static final String Popular_OrderdBy = "downloads";
    public static final int SHARE_ALL = -1;
    public static final int SHARE_FB = 2;
    public static final int SHARE_INSTA = 1;
    public static final String SHARE_LINK = "http://bit.ly/2RoXvae";
    public static final String SHARE_MESSAGE = "Download -StatusJoy- for latest fullscreen video status.";
    public static final int SHARE_WA = 0;
    public static final int SMALL_BANNER_AD = 16;
    public static final String TAG = "InstaDp";
    public static HashMap<String, ArrayList<moneyapp_3>> arrExtraFullScreenList = new HashMap<>();
    public static HashMap<String, ArrayList<moneyapp_3>> arrExtraLandscapeList = new HashMap<>();
    public static ArrayList<String> arrFullScreenKeys = new ArrayList<>();
    public static ArrayList<String> arrFullScreenNames = new ArrayList<>();
    public static ArrayList<String> arrFullScreenTags = new ArrayList<>();
    public static ArrayList<String> arrLandscapeKeys = new ArrayList<>();
    public static ArrayList<String> arrLandscapeNames = new ArrayList<>();
    public static ArrayList<String> arrLandscapeTags = new ArrayList<>();
}
